name: 'Chkk Kubernetes Manifests'
description: 'Check your Kubernetes manifests to catch reliability risks during deployments and upgrades'
inputs:
  suppressions:
    description: 'List of checks to suppress'
    required: false
    default: "[]"
  checklists:
    description: 'List of checks to run'
    required: false
    default: "[]"
  filters:
    description: 'List of filters to apply on Kubernetes manifest'
    required: false
    default: "Secret.data,Secret.data.*"
  continue-on-failure:
    description: 'Suppress failures'
    required: false
    default: "false"
  disable-audit:
    description: 'Disable creation of audit logs'
    required: false
    default: "true"
  cluster-id:
    description: 'Custom cluster ID'
    required: false
    default: ""

outputs:
  config:
    description: 'chkk configuration'
  binary:
    description: 'post-renderer binary'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.suppressions }}
    - ${{ inputs.checklists }}
    - ${{ inputs.filters }}
    - ${{ inputs.continue-on-failure }}
    - ${{ inputs.disable-audit }}
    - ${{ inputs.cluster-id }}
