on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: smuneebahmad/hello-world-action@main
        with:
          checklists: "chkls_ff349092-d781-4e61-87ac-c5cb9fcf2fab"
          continue-on-failure: false
          filters: "ClusterRole.*,ServiceAccount.metadata.*"
#         with:
#           who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          cat ${{ steps.hello.outputs.config }}
          ls -l ${{ steps.hello.outputs.binary }}
