on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: smuneebahmad/hello-world-action@main
        with:
          checklists: "chkls_00000000,chkls111111"
          suppressions: "sup_33333,sup4444444"
          continue-on-failure: true
          filters: "ClusterRole.*,ServiceAccount.metadata.*"
#         with:
#           who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          cat ${{ steps.hello.outputs.config }}
          ls -l ${{ steps.hello.outputs.binary }}
